version: '1.0'
 
services:
  webapp:
    image: skrsoft/my_api:latest
    ports:
      - "80:8080"
    environment:
      MYSQL_DATABASE: api_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: pass1234
      MYSQL_SERVER: db
  db:
    image: mysql:latest
    ports:
      - "8001:3306" 
    environment:
      MYSQL_DATABASE: api_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: pass1234
      MYSQL_SERVER: db
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8002:80
volumes:
  db_data: